import type { Metadata } from "next";
import "./globals.css";
import MusicPlayer from "./MusicPlayer";

export const metadata: Metadata = {
  title: "MiniHackathon 25",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MusicPlayer />
        {children}
      </body>
    </html>
  );
}
